export const data = JSON.parse("{\"key\":\"v-fe30418a\",\"path\":\"/codenotes/python/2023.html\",\"title\":\"爬虫实战2023\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"爬虫实战2023\",\"icon\":\"code\",\"category\":[\"python\",\"爬虫\"],\"tag\":[\"python\",\"爬虫\"],\"sticky\":false,\"star\":true,\"article\":true,\"timeline\":true,\"description\":\"1.实战豆瓣top250 这例用bs加上requests 网址是豆瓣的top250 豆瓣电影 Top 250 (douban.com) 还是一个大概的框架 ```python def main(page): url = 'https://movie.douban.com/top250?start='+ str(page*25)+'&filter=' h...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://gitee.com/lizifan233/mynotes/codenotes/python/2023.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"小uの学习笔记\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"爬虫实战2023\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"1.实战豆瓣top250 这例用bs加上requests 网址是豆瓣的top250 豆瓣电影 Top 250 (douban.com) 还是一个大概的框架 ```python def main(page): url = 'https://movie.douban.com/top250?start='+ str(page*25)+'&filter=' h...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"python\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"爬虫\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"1.实战豆瓣top250\",\"slug\":\"_1-实战豆瓣top250\",\"link\":\"#_1-实战豆瓣top250\",\"children\":[]},{\"level\":2,\"title\":\"2.爬取1000首背景音乐\",\"slug\":\"_2-爬取1000首背景音乐\",\"link\":\"#_2-爬取1000首背景音乐\",\"children\":[]},{\"level\":2,\"title\":\"3.爬取csdn\",\"slug\":\"_3-爬取csdn\",\"link\":\"#_3-爬取csdn\",\"children\":[{\"level\":3,\"title\":\"博客主页博客文章分析\",\"slug\":\"博客主页博客文章分析\",\"link\":\"#博客主页博客文章分析\",\"children\":[]},{\"level\":3,\"title\":\"爬取页面数据\",\"slug\":\"爬取页面数据\",\"link\":\"#爬取页面数据\",\"children\":[]},{\"level\":3,\"title\":\"保存为pdf文件\",\"slug\":\"保存为pdf文件\",\"link\":\"#保存为pdf文件\",\"children\":[]}]},{\"level\":2,\"title\":\"4.觅知网\",\"slug\":\"_4-觅知网\",\"link\":\"#_4-觅知网\",\"children\":[]},{\"level\":2,\"title\":\"5.微博超话爬取\",\"slug\":\"_5-微博超话爬取\",\"link\":\"#_5-微博超话爬取\",\"children\":[{\"level\":3,\"title\":\"构造小时对\",\"slug\":\"构造小时对\",\"link\":\"#构造小时对\",\"children\":[]},{\"level\":3,\"title\":\"主要代码\",\"slug\":\"主要代码\",\"link\":\"#主要代码\",\"children\":[]}]},{\"level\":2,\"title\":\"6.关于图怪网去水印\",\"slug\":\"_6-关于图怪网去水印\",\"link\":\"#_6-关于图怪网去水印\",\"children\":[]},{\"level\":2,\"title\":\"7.第一试卷网\",\"slug\":\"_7-第一试卷网\",\"link\":\"#_7-第一试卷网\",\"children\":[]},{\"level\":2,\"title\":\"8.实战豆瓣图书爬取新书速递\",\"slug\":\"_8-实战豆瓣图书爬取新书速递\",\"link\":\"#_8-实战豆瓣图书爬取新书速递\",\"children\":[]}],\"readingTime\":{\"minutes\":15.19,\"words\":4557},\"filePathRelative\":\"codenotes/python/2023.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
