export const data = JSON.parse("{\"key\":\"v-2432dcd7\",\"path\":\"/codenotes/front_end/form.html\",\"title\":\"表单标签\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"表单（form）是用户输入信息与网页互动的一种形式。大多数情况下，用户提交的信息会发给服务器，比如网站的搜索栏就是表单。 表单由一种或多种的小部件组成，比如输入框、按钮、单选框或复选框。这些小部件称为控件（controls）。 简介 标签用来定义一个表单，所有表单内容放到这个容器元素之中。 上面代码就是表单的基本形式。 下面是一个比较常见的例子。 上面...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://gitee.com/lizifan233/mynotes/codenotes/front_end/form.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"小uの学习笔记\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"表单标签\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"表单（form）是用户输入信息与网页互动的一种形式。大多数情况下，用户提交的信息会发给服务器，比如网站的搜索栏就是表单。 表单由一种或多种的小部件组成，比如输入框、按钮、单选框或复选框。这些小部件称为控件（controls）。 简介 标签用来定义一个表单，所有表单内容放到这个容器元素之中。 上面代码就是表单的基本形式。 下面是一个比较常见的例子。 上面...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"<form>\",\"slug\":\"form\",\"link\":\"#form\",\"children\":[{\"level\":3,\"title\":\"简介\",\"slug\":\"简介\",\"link\":\"#简介\",\"children\":[]},{\"level\":3,\"title\":\"enctype 属性\",\"slug\":\"enctype-属性\",\"link\":\"#enctype-属性\",\"children\":[]}]},{\"level\":2,\"title\":\"<fieldset>，<legend>\",\"slug\":\"fieldset-legend\",\"link\":\"#fieldset-legend\",\"children\":[]},{\"level\":2,\"title\":\"<label>\",\"slug\":\"label\",\"link\":\"#label\",\"children\":[]},{\"level\":2,\"title\":\"<input>\",\"slug\":\"input\",\"link\":\"#input\",\"children\":[{\"level\":3,\"title\":\"简介\",\"slug\":\"简介-1\",\"link\":\"#简介-1\",\"children\":[]},{\"level\":3,\"title\":\"类型\",\"slug\":\"类型\",\"link\":\"#类型\",\"children\":[]}]},{\"level\":2,\"title\":\"<button>\",\"slug\":\"button\",\"link\":\"#button\",\"children\":[]},{\"level\":2,\"title\":\"<select>\",\"slug\":\"select\",\"link\":\"#select\",\"children\":[]},{\"level\":2,\"title\":\"<option>，<optgroup>\",\"slug\":\"option-optgroup\",\"link\":\"#option-optgroup\",\"children\":[]},{\"level\":2,\"title\":\"<datalist>\",\"slug\":\"datalist\",\"link\":\"#datalist\",\"children\":[]},{\"level\":2,\"title\":\"<textarea>\",\"slug\":\"textarea\",\"link\":\"#textarea\",\"children\":[]},{\"level\":2,\"title\":\"<output>\",\"slug\":\"output\",\"link\":\"#output\",\"children\":[]},{\"level\":2,\"title\":\"<progress>\",\"slug\":\"progress\",\"link\":\"#progress\",\"children\":[]},{\"level\":2,\"title\":\"<meter>\",\"slug\":\"meter\",\"link\":\"#meter\",\"children\":[]},{\"level\":2,\"title\":\"参考链接\",\"slug\":\"参考链接\",\"link\":\"#参考链接\",\"children\":[]}],\"readingTime\":{\"minutes\":31.4,\"words\":9421},\"filePathRelative\":\"codenotes/front_end/form.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
