<template><div><h1 id="多媒体标签" tabindex="-1"><a class="header-anchor" href="#多媒体标签" aria-hidden="true">#</a> 多媒体标签</h1>
<p>除了图像，网页还可以放置视频和音频。</p>
<h2 id="video" tabindex="-1"><a class="header-anchor" href="#video" aria-hidden="true">#</a> <code v-pre>&lt;video&gt;</code></h2>
<p><code v-pre>&lt;video&gt;</code>标签是一个块级元素，用于放置视频。如果浏览器支持加载的视频格式，就会显示一个播放器，否则显示<code v-pre>&lt;video&gt;</code>内部的子元素。</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>video</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>example.mp4<span class="token punctuation">"</span></span> <span class="token attr-name">controls</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span><span class="token punctuation">></span></span>你的浏览器不支持 HTML5 视频，请下载<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>example.mp4<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>视频文件<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span>。<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>video</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，如果浏览器不支持该种格式的视频，就会显示<code v-pre>&lt;video&gt;</code>内部的文字提示。</p>
<p><code v-pre>&lt;video&gt;</code>有以下属性。</p>
<ul>
<li><code v-pre>src</code>：视频文件的网址。</li>
<li><code v-pre>controls</code>：播放器是否显示控制栏。该属性是布尔属性，不用赋值，只要写上属性名，就表示打开。如果不想使用浏览器默认的播放器，而想使用自定义播放器，就不要使用该属性。</li>
<li><code v-pre>width</code>：视频播放器的宽度，单位像素。</li>
<li><code v-pre>height</code>：视频播放器的高度，单位像素。</li>
<li><code v-pre>autoplay</code>：视频是否自动播放，该属性为布尔属性。</li>
<li><code v-pre>loop</code>：视频是否循环播放，该属性为布尔属性。</li>
<li><code v-pre>muted</code>：是否默认静音，该属性为布尔属性。</li>
<li><code v-pre>poster</code>：视频播放器的封面图片的 URL。</li>
<li><code v-pre>preload</code>：视频播放之前，是否缓冲视频文件。这个属性仅适合没有设置<code v-pre>autoplay</code>的情况。它有三个值，分别是<code v-pre>none</code>（不缓冲）、<code v-pre>metadata</code>（仅仅缓冲视频文件的元数据）、<code v-pre>auto</code>（可以缓冲整个文件）。</li>
<li><code v-pre>playsinline</code>：iPhone 的 Safari 浏览器播放视频时，会自动全屏，该属性可以禁止这种行为。该属性为布尔属性。</li>
<li><code v-pre>crossorigin</code>：是否采用跨域的方式加载视频。它可以取两个值，分别是<code v-pre>anonymous</code>（跨域请求时，不发送用户凭证，主要是 Cookie），<code v-pre>use-credentials</code>（跨域时发送用户凭证）。</li>
<li><code v-pre>currentTime</code>：指定当前播放位置（双精度浮点数，单位为秒）。如果尚未开始播放，则会从这个属性指定的位置开始播放。</li>
<li><code v-pre>duration</code>：该属性只读，指示时间轴上的持续播放时间（总长度），值为双精度浮点数（单位为秒）。如果是流媒体，没有已知的结束时间，属性值为<code v-pre>+Infinity</code>。</li>
</ul>
<p>下面是一个例子。</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>video</span> <span class="token attr-name">width</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>400<span class="token punctuation">"</span></span> <span class="token attr-name">height</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>400<span class="token punctuation">"</span></span>
       <span class="token attr-name">autoplay</span> <span class="token attr-name">loop</span> <span class="token attr-name">muted</span>
       <span class="token attr-name">poster</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>poster.png<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>video</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，视频播放器的大小是 400 x 400，会自动播放和循环播放，并且静音，还带有封面图。这是网站首页背景视频的常见写法。</p>
<p>HTML 标准没有规定浏览器需要支持哪些视频格式，完全由浏览器厂商自己决定。为了避免浏览器不支持视频格式，可以使用<code v-pre>&lt;source&gt;</code>标签，放置同一个视频的多种格式。</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>video</span> <span class="token attr-name">controls</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>source</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>example.mp4<span class="token punctuation">"</span></span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>video/mp4<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>source</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>example.webm<span class="token punctuation">"</span></span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>video/webm<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span><span class="token punctuation">></span></span>你的浏览器不支持 HTML5 视频，请下载<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>example.mp4<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>视频文件<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span>。<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>video</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，<code v-pre>&lt;source&gt;</code>标签的<code v-pre>type</code>属性的值是视频文件的 MIME 类型，上例指定了两种格式的视频文件：MP4 和 WebM。如果浏览器支持 MP4，就加载 MP4 格式的视频，不再往下执行了。如果不支持 MP4，就检查是否支持 WebM，如果还是不支持，则显示提示。</p>
<h2 id="audio" tabindex="-1"><a class="header-anchor" href="#audio" aria-hidden="true">#</a> <code v-pre>&lt;audio&gt;</code></h2>
<p><code v-pre>&lt;audio&gt;</code>标签是一个块级元素，用于放置音频，用法与<code v-pre>&lt;video&gt;</code>标签基本一致。</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>audio</span> <span class="token attr-name">controls</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>source</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>foo.mp3<span class="token punctuation">"</span></span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>audio/mp3<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>source</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>foo.ogg<span class="token punctuation">"</span></span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>audio/ogg<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span><span class="token punctuation">></span></span>你的浏览器不支持 HTML5 音频，请直接下载<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>foo.mp3<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>音频文件<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span>。<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>audio</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，<code v-pre>&lt;audio&gt;</code>标签内部使用<code v-pre>&lt;source&gt;</code>标签，指定了两种音频格式：优先使用 MP3 格式，如果浏览器不支持则使用 Ogg 格式。如果浏览器不能播放音频，则提供下载链接。</p>
<p><code v-pre>&lt;audio&gt;</code>标签的属性与<code v-pre>&lt;video&gt;</code>标签类似，参见上一节。</p>
<ul>
<li><code v-pre>autoplay</code>：是否自动播放，布尔属性。</li>
<li><code v-pre>controls</code>：是否显示播放工具栏，布尔属性。如果不设置，浏览器不显示播放界面，通常用于背景音乐。</li>
<li><code v-pre>crossorigin</code>：是否使用跨域方式请求。</li>
<li><code v-pre>loop</code>：是否循环播放，布尔属性。</li>
<li><code v-pre>muted</code>：是否静音，布尔属性。</li>
<li><code v-pre>preload</code>：音频文件的缓冲设置。</li>
<li><code v-pre>src</code>：音频文件网址。</li>
</ul>
<h2 id="track" tabindex="-1"><a class="header-anchor" href="#track" aria-hidden="true">#</a> <code v-pre>&lt;track&gt;</code></h2>
<p><code v-pre>&lt;track&gt;</code>标签用于指定视频的字幕，格式是 WebVTT （<code v-pre>.vtt</code>文件），放置在<code v-pre>&lt;video&gt;</code>标签内部。它是一个单独使用的标签，没有结束标签。</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>video</span> <span class="token attr-name">controls</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>sample.mp4<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
   <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>track</span> <span class="token attr-name">label</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>英文<span class="token punctuation">"</span></span> <span class="token attr-name">kind</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>subtitles<span class="token punctuation">"</span></span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>subtitles_en.vtt<span class="token punctuation">"</span></span> <span class="token attr-name">srclang</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>en<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
   <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>track</span> <span class="token attr-name">label</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>中文<span class="token punctuation">"</span></span> <span class="token attr-name">kind</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>subtitles<span class="token punctuation">"</span></span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>subtitles_cn.vtt<span class="token punctuation">"</span></span> <span class="token attr-name">srclang</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>cn<span class="token punctuation">"</span></span> <span class="token attr-name">default</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>video</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码指定视频文件的英文字幕和中文字幕。</p>
<p><code v-pre>&lt;track&gt;</code>标签有以下属性。</p>
<ul>
<li><code v-pre>label</code>：播放器显示的字幕名称，供用户选择。</li>
<li><code v-pre>kind</code>：字幕的类型，默认是<code v-pre>subtitles</code>，表示将原始声音成翻译外国文字，比如英文视频提供中文字幕。另一个常见的值是<code v-pre>captions</code>，表示原始声音的文字描述，通常是视频原始使用的语言，比如英文视频提供英文字幕。</li>
<li><code v-pre>src</code>：vtt 字幕文件的网址。</li>
<li><code v-pre>srclang</code>：字幕的语言，必须是有效的语言代码。</li>
<li><code v-pre>default</code>：是否默认打开，布尔属性。</li>
</ul>
<h2 id="source" tabindex="-1"><a class="header-anchor" href="#source" aria-hidden="true">#</a> <code v-pre>&lt;source&gt;</code></h2>
<p><code v-pre>&lt;source&gt;</code>标签用于<code v-pre>&lt;picture&gt;</code>、<code v-pre>&lt;video&gt;</code>、<code v-pre>&lt;audio&gt;</code>的内部，用于指定一项外部资源。单标签是单独使用的，没有结束标签。</p>
<p>它有如下属性，具体示例请参见相应的容器标签。</p>
<ul>
<li><code v-pre>type</code>：指定外部资源的 MIME 类型。</li>
<li><code v-pre>src</code>：指定源文件，用于<code v-pre>&lt;video&gt;</code>和<code v-pre>&lt;audio&gt;</code>。</li>
<li><code v-pre>srcset</code>：指定不同条件下加载的图像文件，用于<code v-pre>&lt;picture&gt;</code>。</li>
<li><code v-pre>media</code>：指定媒体查询表达式，用于<code v-pre>&lt;picture&gt;</code>。</li>
<li><code v-pre>sizes</code>：指定不同设备的显示大小，用于<code v-pre>&lt;picture&gt;</code>，必须跟<code v-pre>srcset</code>搭配使用。</li>
</ul>
<h2 id="embed" tabindex="-1"><a class="header-anchor" href="#embed" aria-hidden="true">#</a> <code v-pre>&lt;embed&gt;</code></h2>
<p><code v-pre>&lt;embed&gt;</code>标签用于嵌入外部内容，这个外部内容通常由浏览器插件负责控制。由于浏览器的默认插件都不一致，很可能不是所有浏览器的用户都能访问这部分内容，建议谨慎使用。</p>
<p>下面是嵌入视频播放器的例子。</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>embed</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>video/webm<span class="token punctuation">"</span></span>
       <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>/media/examples/flower.mp4<span class="token punctuation">"</span></span>
       <span class="token attr-name">width</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>250<span class="token punctuation">"</span></span>
       <span class="token attr-name">height</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>200<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码嵌入的视频，将由浏览器插件负责控制。如果浏览器没有安装 MP4 插件，视频就无法播放。</p>
<p><code v-pre>&lt;embed&gt;</code>标签具有如下的通用属性。</p>
<ul>
<li><code v-pre>height</code>：显示高度，单位为像素，不允许百分比。</li>
<li><code v-pre>width</code>：显示宽度，单位为像素，不允许百分比。</li>
<li><code v-pre>src</code>：嵌入的资源的 URL。</li>
<li><code v-pre>type</code>：嵌入资源的 MIME 类型。</li>
</ul>
<p>浏览器通过<code v-pre>type</code>属性得到嵌入资源的 MIME 类型，一旦该种类型已经被某个插件注册了，就会启动该插件，负责处理嵌入的资源。</p>
<p>下面是 QuickTime 插件播放 MOV 视频文件的例子。</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>embed</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>video/quicktime<span class="token punctuation">"</span></span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>movie.mov<span class="token punctuation">"</span></span> <span class="token attr-name">width</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>640<span class="token punctuation">"</span></span> <span class="token attr-name">height</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>480<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>下面是启动 Flash 插件的例子。</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>embed</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>whoosh.swf<span class="token punctuation">"</span></span> <span class="token attr-name">quality</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>medium<span class="token punctuation">"</span></span>
       <span class="token attr-name">bgcolor</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>#ffffff<span class="token punctuation">"</span></span> <span class="token attr-name">width</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>550<span class="token punctuation">"</span></span> <span class="token attr-name">height</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>400<span class="token punctuation">"</span></span>
       <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>whoosh<span class="token punctuation">"</span></span> <span class="token attr-name">align</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>middle<span class="token punctuation">"</span></span> <span class="token attr-name">allowScriptAccess</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>sameDomain<span class="token punctuation">"</span></span>
       <span class="token attr-name">allowFullScreen</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>false<span class="token punctuation">"</span></span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>application/x-shockwave-flash<span class="token punctuation">"</span></span>
       <span class="token attr-name">pluginspage</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>http://www.macromedia.com/go/getflashplayer<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，如果浏览器没有安装 Flash 插件，就会提示去<code v-pre>pluginspage</code>属性指定的网址下载。</p>
<h2 id="object-param" tabindex="-1"><a class="header-anchor" href="#object-param" aria-hidden="true">#</a> <code v-pre>&lt;object&gt;</code>，<code v-pre>&lt;param&gt;</code></h2>
<p><code v-pre>&lt;object&gt;</code>标签作用跟<code v-pre>&lt;embed&gt;</code>相似，也是插入外部资源，由浏览器插件处理。它可以视为<code v-pre>&lt;embed&gt;</code>的替代品，有标准化行为，只限于插入少数几种通用资源，没有历史遗留问题，因此更推荐使用。</p>
<p>下面是插入 PDF 文件的例子。</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>object</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>application/pdf<span class="token punctuation">"</span></span>
    <span class="token attr-name">data</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>/media/examples/In-CC0.pdf<span class="token punctuation">"</span></span>
    <span class="token attr-name">width</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>250<span class="token punctuation">"</span></span>
    <span class="token attr-name">height</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>200<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>object</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，如果浏览器安装了 PDF 插件，就会在网页显示 PDF 浏览窗口。</p>
<p><code v-pre>&lt;object&gt;</code>具有如下的通用属性。</p>
<ul>
<li><code v-pre>data</code>：嵌入的资源的 URL。</li>
<li><code v-pre>form</code>：当前网页中相关联表单的<code v-pre>id</code>属性（如果有的话）。</li>
<li><code v-pre>height</code>：资源的显示高度，单位为像素，不能使用百分比。</li>
<li><code v-pre>width</code>：资源的显示宽度，单位为像素，不能使用百分比。</li>
<li><code v-pre>type</code>：资源的 MIME 类型。</li>
<li><code v-pre>typemustmatch</code>：布尔属性，表示<code v-pre>data</code>属性与<code v-pre>type</code>属性是否必须匹配。</li>
</ul>
<p>下面是插入 Flash 影片的例子。</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>object</span> <span class="token attr-name">data</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>movie.swf<span class="token punctuation">"</span></span>
  <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>application/x-shockwave-flash<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>object</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>&lt;object&gt;</code>标签是一个容器元素，内部可以使用<code v-pre>&lt;param&gt;</code>标签，给出插件所需要的运行参数。</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>object</span> <span class="token attr-name">data</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>movie.swf<span class="token punctuation">"</span></span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>application/x-shockwave-flash<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>param</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>foo<span class="token punctuation">"</span></span> <span class="token attr-name">value</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>bar<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>object</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


