export const data = JSON.parse("{\"key\":\"v-b966791e\",\"path\":\"/codenotes/algorithm/leetcode/easy.html\",\"title\":\"简单题目\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"简单题目\",\"icon\":\"code\",\"category\":[\"算法\",\"leetcode\"],\"tag\":[\"算法\",\"leetcode\"],\"sticky\":false,\"star\":true,\"article\":true,\"timeline\":true,\"description\":\"简单题目 1.两数之和 给定一个整数数组 nums 和一个整数目标值 target，请你在该数组中找出 和为目标值 target 的那 两个 整数，并返回它们的数组下标。 你可以假设每种输入只会对应一个答案。但是，数组中同一个元素在答案里不能重复出现。 你可以按任意顺序返回答案。 示例 1： ``` 输入：nums = [2,7,11,15], tar...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://gitee.com/lizifan233/mynotes/codenotes/algorithm/leetcode/easy.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"小uの学习笔记\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"简单题目\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"简单题目 1.两数之和 给定一个整数数组 nums 和一个整数目标值 target，请你在该数组中找出 和为目标值 target 的那 两个 整数，并返回它们的数组下标。 你可以假设每种输入只会对应一个答案。但是，数组中同一个元素在答案里不能重复出现。 你可以按任意顺序返回答案。 示例 1： ``` 输入：nums = [2,7,11,15], tar...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"算法\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"leetcode\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"简单题目\",\"slug\":\"简单题目\",\"link\":\"#简单题目\",\"children\":[]},{\"level\":2,\"title\":\"1.两数之和\",\"slug\":\"_1-两数之和\",\"link\":\"#_1-两数之和\",\"children\":[]},{\"level\":2,\"title\":\"9.回文数\",\"slug\":\"_9-回文数\",\"link\":\"#_9-回文数\",\"children\":[]},{\"level\":2,\"title\":\"13.罗马数字转整数\",\"slug\":\"_13-罗马数字转整数\",\"link\":\"#_13-罗马数字转整数\",\"children\":[]},{\"level\":2,\"title\":\"14.最长公共前缀\",\"slug\":\"_14-最长公共前缀\",\"link\":\"#_14-最长公共前缀\",\"children\":[]},{\"level\":2,\"title\":\"20.有效的括号\",\"slug\":\"_20-有效的括号\",\"link\":\"#_20-有效的括号\",\"children\":[]},{\"level\":2,\"title\":\"21.合并两个有序序列\",\"slug\":\"_21-合并两个有序序列\",\"link\":\"#_21-合并两个有序序列\",\"children\":[]},{\"level\":2,\"title\":\"26.删除有序数组的重复项\",\"slug\":\"_26-删除有序数组的重复项\",\"link\":\"#_26-删除有序数组的重复项\",\"children\":[]},{\"level\":2,\"title\":\"27.移除元素\",\"slug\":\"_27-移除元素\",\"link\":\"#_27-移除元素\",\"children\":[]},{\"level\":2,\"title\":\"35.搜索插入位置\",\"slug\":\"_35-搜索插入位置\",\"link\":\"#_35-搜索插入位置\",\"children\":[]},{\"level\":2,\"title\":\"58.最后一个单词的长度\",\"slug\":\"_58-最后一个单词的长度\",\"link\":\"#_58-最后一个单词的长度\",\"children\":[]},{\"level\":2,\"title\":\"66.加一\",\"slug\":\"_66-加一\",\"link\":\"#_66-加一\",\"children\":[]},{\"level\":2,\"title\":\"67.二进制求和\",\"slug\":\"_67-二进制求和\",\"link\":\"#_67-二进制求和\",\"children\":[]}],\"readingTime\":{\"minutes\":21.6,\"words\":6481},\"filePathRelative\":\"codenotes/algorithm/leetcode/easy.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
