export const pagesRoutes = [
  ["v-8daa1a0e","/",{"t":"个人主页","i":"home","y":"h","r":{"minutes":0.34,"words":103}},["/index.html","/README.md"]],
  ["v-145ac574","/blog/",{"t":"","y":"h","r":{"minutes":0.29,"words":86}},["/blog/index.html","/blog/README.md"]],
  ["v-4c083800","/quicknav/",{"t":"快速导航","i":"navigation","y":"a","e":"搜索引擎 开源社区 优质博客 在线工具 在线教程 文档相关 其他导航","c":["快速导航"],"g":["优质博客","搜索引擎"],"u":false,"r":{"minutes":3.5,"words":1051}},["/quicknav/index.html","/quicknav/README.md"]],
  ["v-7208bd18","/codenotes/",{"t":"简介","i":"code","y":"a","e":"本人联系方式 微信17713088356 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 书写这个博客也是一时兴起。但是总想着记录些什么东西。所以就咬咬牙完成了这个的一套搭建。 首先我来介绍一下自己 目前就读于河北科技师范学院 (https://www.hevttc.edu.cn/)计算机专业的学生。主要研究java...","c":["目录","导航"],"g":["目录","导航"],"u":false,"r":{"minutes":1.99,"words":596}},["/codenotes/index.html","/codenotes/README.md"]],
  ["v-aafb2f66","/codenotes/algorithm/heima.html",{"t":"数据结构与算法(黑马)","i":"code","y":"a","e":"一. 初识算法 1.1 什么是算法？ 定义 在数学和计算机科学领域，算法是一系列有限的严谨指令，通常用于解决一类特定问题或执行计算\r In mathematics and computer science, an algorithm (/ˈælɡərɪðəm/) is a finite sequence of rigorous instructions...","c":["算法"],"g":["算法"],"u":false,"r":{"minutes":176.88,"words":53064}},["/codenotes/algorithm/heima","/codenotes/algorithm/heima.md"]],
  ["v-1c50bb60","/codenotes/front_end/HTML.html",{"t":"HTML","i":"code","y":"a","e":"HTML 语言简介 概述 HTML 是网页使用的语言，定义了网页的结构和内容。浏览器访问网站，其实就是从服务器下载 HTML 代码，然后渲染出网页。 HTML 的全名是“超文本标记语言”（HyperText Markup Language），上个世纪90年代由欧洲核子研究中心的物理学家蒂姆·伯纳斯-李（Tim Berners-Lee）发明。它的最大特点...","c":["HTML","前端"],"g":["HTML","前端"],"u":false,"r":{"minutes":132.5,"words":39750}},["/codenotes/front_end/HTML","/codenotes/front_end/HTML.md"]],
  ["v-20e31015","/codenotes/front_end/WebApi.html",{"t":"WebApi","i":"code","y":"a","e":"WebApi 这个只作为一个了解就可以了 Canvas API 概述 元素用于生成图像。它本身就像一个画布，JavaScript 通过操作它的 API，在上面生成图像。它的底层是一个个像素，基本上是一个可以用 JavaScript 操作的位图（bitmap）。 它与 SVG 图像的区别在于，是脚本调用各种方法生成图像，SVG 则是一个 XML 文件，通...","c":["WebApi","前端"],"g":["WebApi","前端"],"u":false,"r":{"minutes":123.66,"words":37098}},["/codenotes/front_end/WebApi","/codenotes/front_end/WebApi.md"]],
  ["v-6e102574","/codenotes/Java/java%E5%9F%BA%E7%A1%80.html",{"t":"java基础","i":"code","y":"a","e":"黑白米白色文学作品中式文化宣传中文书籍封面 (1) Java ​ 这个是书写的第一本小册，用来详细的去复习java的基础的内容，这里会记录一些我从其他书籍上看到的相关的介绍，简介等，以及自己对于这个的理解，以及一些详细的案例。综合考虑来制作这样的一本java基础书籍，会持续的去补充这里的东西。 java概述以及环境变量的配置 为什么选择java 很简单...","c":["java","javaSE"],"g":["java","javaSE"],"u":false,"r":{"minutes":139.55,"words":41865}},["/codenotes/Java/java基础.html","/codenotes/Java/java%E5%9F%BA%E7%A1%80","/codenotes/Java/java基础.md","/codenotes/Java/java%E5%9F%BA%E7%A1%80.md"]],
  ["v-7dcf9315","/codenotes/Java/java%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html",{"t":"java面向对象","i":"code","y":"a","e":"前言 这本书励志与用这一本书讲透java的面向对象，其实面向对象是一个非常常见的场景在java里面，所以这个是每一个学习java要实现掌握的，并且详细掌握的，为了以后我们去学习一些框架，打下基础。 什么是面向对象 相信很多Java开发者，在最初接触Java的时候就听说过，Java是一种面向对象的开发语言，那么什么是面向对象呢？ 首先，所谓面向对象，其实...","c":["java","面向对象"],"g":["java","面向对象"],"u":false,"r":{"minutes":139.28,"words":41785}},["/codenotes/Java/java面向对象.html","/codenotes/Java/java%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1","/codenotes/Java/java面向对象.md","/codenotes/Java/java%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.md"]],
  ["v-e19b8b2e","/codenotes/Java/spring6.html",{"t":"Spring6","i":"code","y":"a","e":"image-20221209110043449 1、概述 1.1、Spring是什么？ Spring 是一款主流的 Java EE 轻量级开源框架 ，Spring 由“Spring 之父”Rod Johnson 提出并创立，其目的是用于简化 Java 企业级应用的开发难度和开发周期。Spring的用途不仅限于服务器端的开发。从简单性、可测试性和松耦合的...","c":["java","Spring"],"g":["java","Spring"],"u":false,"r":{"minutes":107.88,"words":32363}},["/codenotes/Java/spring6","/codenotes/Java/spring6.md"]],
  ["v-b966791e","/codenotes/algorithm/leetcode/easy.html",{"t":"简单题目","i":"code","y":"a","e":"简单题目 1.两数之和 给定一个整数数组 nums 和一个整数目标值 target，请你在该数组中找出 和为目标值 target 的那 两个 整数，并返回它们的数组下标。 你可以假设每种输入只会对应一个答案。但是，数组中同一个元素在答案里不能重复出现。 你可以按任意顺序返回答案。 示例 1： ``` 输入：nums = [2,7,11,15], tar...","c":["算法","leetcode"],"g":["算法","leetcode"],"u":false,"r":{"minutes":21.6,"words":6481}},["/codenotes/algorithm/leetcode/easy","/codenotes/algorithm/leetcode/easy.md"]],
  ["v-075e1028","/codenotes/algorithm/leetcode/hard.html",{"t":"困难题目","i":"code","y":"a","e":"这个明年2024了在做。","c":["算法","leetcode"],"g":["算法","leetcode"],"u":false,"r":{"minutes":0.37,"words":110}},["/codenotes/algorithm/leetcode/hard","/codenotes/algorithm/leetcode/hard.md"]],
  ["v-44323984","/codenotes/algorithm/leetcode/middle.html",{"t":"中等题目","i":"code","y":"a","e":"中等题目 2.两数相加 给你两个 非空 的链表，表示两个非负的整数。它们每位数字都是按照 逆序 的方式存储的，并且每个节点只能存储 一位 数字。 请你将两个数相加，并以相同形式返回一个表示和的链表。 你可以假设除了数字 0 之外，这两个数都不会以 0 开头。 img ``` 输入：l1 = [2,4,3], l2 = [5,6,4] 输出：[7,0,8...","c":["算法","leetcode"],"g":["算法","leetcode"],"u":false,"r":{"minutes":3.53,"words":1059}},["/codenotes/algorithm/leetcode/middle","/codenotes/algorithm/leetcode/middle.md"]],
  ["v-fe30418a","/codenotes/python/2023.html",{"t":"爬虫实战2023","i":"code","y":"a","e":"1.实战豆瓣top250 这例用bs加上requests 网址是豆瓣的top250 豆瓣电影 Top 250 (douban.com) 还是一个大概的框架 ```python def main(page): url = 'https://movie.douban.com/top250?start='+ str(page*25)+'&filter=' h...","c":["python","爬虫"],"g":["python","爬虫"],"u":false,"r":{"minutes":15.19,"words":4557}},["/codenotes/python/2023","/codenotes/python/2023.md"]],
  ["v-7a3136ea","/codenotes/python/auto.html",{"t":"办公自动化","i":"code","y":"a","e":"1.在某个文件目录下，找到某个文件 非递归 ```python import os curdir = os.path.dirname(os.path.abspath(_name__)) parentdir = os.path.dirname(curdir) findpath = os.path.join(parentdir, 'res') while ...","c":["python","办公"],"g":["python","办公"],"u":false,"r":{"minutes":15.96,"words":4788}},["/codenotes/python/auto","/codenotes/python/auto.md"]],
  ["v-3706649a","/404.html",{"t":"","y":"p"},["/404"]],
  ["v-5bc93818","/category/",{"t":"分类","y":"p"},["/category/index.html"]],
  ["v-744d024e","/tag/",{"t":"标签","y":"p"},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"t":"文章","y":"p"},["/article/index.html"]],
  ["v-75ed4ea4","/encrypted/",{"t":"加密","y":"p"},["/encrypted/index.html"]],
  ["v-d804e652","/slide/",{"t":"幻灯片","y":"p"},["/slide/index.html"]],
  ["v-154dc4c4","/star/",{"t":"收藏","y":"p"},["/star/index.html"]],
  ["v-01560935","/timeline/",{"t":"时间轴","y":"p"},["/timeline/index.html"]],
  ["v-1eaeb558","/category/%E5%BF%AB%E9%80%9F%E5%AF%BC%E8%88%AA/",{"t":"快速导航 分类","y":"p"},["/category/快速导航/","/category/%E5%BF%AB%E9%80%9F%E5%AF%BC%E8%88%AA/index.html"]],
  ["v-48f9b645","/tag/%E4%BC%98%E8%B4%A8%E5%8D%9A%E5%AE%A2/",{"t":"优质博客 标签","y":"p"},["/tag/优质博客/","/tag/%E4%BC%98%E8%B4%A8%E5%8D%9A%E5%AE%A2/index.html"]],
  ["v-f96d488c","/category/%E7%9B%AE%E5%BD%95/",{"t":"目录 分类","y":"p"},["/category/目录/","/category/%E7%9B%AE%E5%BD%95/index.html"]],
  ["v-36f81cca","/tag/%E6%90%9C%E7%B4%A2%E5%BC%95%E6%93%8E/",{"t":"搜索引擎 标签","y":"p"},["/tag/搜索引擎/","/tag/%E6%90%9C%E7%B4%A2%E5%BC%95%E6%93%8E/index.html"]],
  ["v-3c1a6df0","/category/%E5%AF%BC%E8%88%AA/",{"t":"导航 分类","y":"p"},["/category/导航/","/category/%E5%AF%BC%E8%88%AA/index.html"]],
  ["v-a59eec78","/tag/%E7%9B%AE%E5%BD%95/",{"t":"目录 标签","y":"p"},["/tag/目录/","/tag/%E7%9B%AE%E5%BD%95/index.html"]],
  ["v-06be9332","/category/%E7%AE%97%E6%B3%95/",{"t":"算法 分类","y":"p"},["/category/算法/","/category/%E7%AE%97%E6%B3%95/index.html"]],
  ["v-66019bfa","/tag/%E5%AF%BC%E8%88%AA/",{"t":"导航 标签","y":"p"},["/tag/导航/","/tag/%E5%AF%BC%E8%88%AA/index.html"]],
  ["v-581e04cc","/category/html/",{"t":"HTML 分类","y":"p"},["/category/html/index.html"]],
  ["v-2687e471","/tag/%E7%AE%97%E6%B3%95/",{"t":"算法 标签","y":"p"},["/tag/算法/","/tag/%E7%AE%97%E6%B3%95/index.html"]],
  ["v-e9c7e408","/category/%E5%89%8D%E7%AB%AF/",{"t":"前端 分类","y":"p"},["/category/前端/","/category/%E5%89%8D%E7%AB%AF/index.html"]],
  ["v-288e2c56","/tag/html/",{"t":"HTML 标签","y":"p"},["/tag/html/index.html"]],
  ["v-701470de","/category/webapi/",{"t":"WebApi 分类","y":"p"},["/category/webapi/index.html"]],
  ["v-95f987f4","/tag/%E5%89%8D%E7%AB%AF/",{"t":"前端 标签","y":"p"},["/tag/前端/","/tag/%E5%89%8D%E7%AB%AF/index.html"]],
  ["v-5831b135","/category/java/",{"t":"java 分类","y":"p"},["/category/java/index.html"]],
  ["v-3cfa349b","/tag/webapi/",{"t":"WebApi 标签","y":"p"},["/tag/webapi/index.html"]],
  ["v-128b43a3","/category/javase/",{"t":"javaSE 分类","y":"p"},["/category/javase/index.html"]],
  ["v-28a1d8bf","/tag/java/",{"t":"java 标签","y":"p"},["/tag/java/index.html"]],
  ["v-a3a87d64","/category/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1/",{"t":"面向对象 分类","y":"p"},["/category/面向对象/","/category/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1/index.html"]],
  ["v-f0e09ea6","/tag/javase/",{"t":"javaSE 标签","y":"p"},["/tag/javase/index.html"]],
  ["v-08073caa","/category/spring/",{"t":"Spring 分类","y":"p"},["/category/spring/index.html"]],
  ["v-728b40d8","/tag/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1/",{"t":"面向对象 标签","y":"p"},["/tag/面向对象/","/tag/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1/index.html"]],
  ["v-011c83e2","/category/leetcode/",{"t":"leetcode 分类","y":"p"},["/category/leetcode/index.html"]],
  ["v-7d0ba9b4","/tag/spring/",{"t":"Spring 标签","y":"p"},["/tag/spring/index.html"]],
  ["v-78cbe7bb","/category/python/",{"t":"python 分类","y":"p"},["/category/python/index.html"]],
  ["v-46b9d66c","/tag/leetcode/",{"t":"leetcode 标签","y":"p"},["/tag/leetcode/index.html"]],
  ["v-54a7b1d7","/category/%E7%88%AC%E8%99%AB/",{"t":"爬虫 分类","y":"p"},["/category/爬虫/","/category/%E7%88%AC%E8%99%AB/index.html"]],
  ["v-245f5676","/tag/python/",{"t":"python 标签","y":"p"},["/tag/python/index.html"]],
  ["v-56cb89d5","/category/%E5%8A%9E%E5%85%AC/",{"t":"办公 分类","y":"p"},["/category/办公/","/category/%E5%8A%9E%E5%85%AC/index.html"]],
  ["v-7e8edfe1","/tag/%E7%88%AC%E8%99%AB/",{"t":"爬虫 标签","y":"p"},["/tag/爬虫/","/tag/%E7%88%AC%E8%99%AB/index.html"]],
  ["v-fe9a9042","/tag/%E5%8A%9E%E5%85%AC/",{"t":"办公 标签","y":"p"},["/tag/办公/","/tag/%E5%8A%9E%E5%85%AC/index.html"]],
]
