export const data = JSON.parse("{\"key\":\"v-838ce624\",\"path\":\"/projects/zatan/9/2.html\",\"title\":\"十个Lambda表达式小技巧\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"十个Lambda表达式小技巧\",\"icon\":\"code\",\"category\":[\"技术杂谈\"],\"tag\":[\"技术杂谈\"],\"sticky\":false,\"star\":true,\"article\":true,\"timeline\":true,\"description\":\"进行集合遍历 ```java List list = Arrays.asList(\\\"apple\\\", \\\"banner\\\", \\\"orange\\\"); for (String s : list) { System.out.println(s); } ``` 这个是一个普通的遍历方法。 之后我们来看经过lambda优化后的 ```java list.forEach...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mydocs.guoyaxue.top/projects/zatan/9/2.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"小uの学习笔记\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"十个Lambda表达式小技巧\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"进行集合遍历 ```java List list = Arrays.asList(\\\"apple\\\", \\\"banner\\\", \\\"orange\\\"); for (String s : list) { System.out.println(s); } ``` 这个是一个普通的遍历方法。 之后我们来看经过lambda优化后的 ```java list.forEach...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2023-09-02T07:39:46.000Z\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"技术杂谈\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2023-09-02T07:39:46.000Z\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"进行集合遍历\",\"slug\":\"进行集合遍历\",\"link\":\"#进行集合遍历\",\"children\":[]},{\"level\":2,\"title\":\"排序\",\"slug\":\"排序\",\"link\":\"#排序\",\"children\":[]},{\"level\":2,\"title\":\"过滤\",\"slug\":\"过滤\",\"link\":\"#过滤\",\"children\":[]},{\"level\":2,\"title\":\"映射\",\"slug\":\"映射\",\"link\":\"#映射\",\"children\":[]},{\"level\":2,\"title\":\"规约\",\"slug\":\"规约\",\"link\":\"#规约\",\"children\":[]},{\"level\":2,\"title\":\"分组\",\"slug\":\"分组\",\"link\":\"#分组\",\"children\":[]},{\"level\":2,\"title\":\"函数式接口\",\"slug\":\"函数式接口\",\"link\":\"#函数式接口\",\"children\":[]},{\"level\":2,\"title\":\"创建线程\",\"slug\":\"创建线程\",\"link\":\"#创建线程\",\"children\":[]},{\"level\":2,\"title\":\"进行optional操作\",\"slug\":\"进行optional操作\",\"link\":\"#进行optional操作\",\"children\":[]},{\"level\":2,\"title\":\"进行stream的流水\",\"slug\":\"进行stream的流水\",\"link\":\"#进行stream的流水\",\"children\":[]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[]}],\"git\":{\"createdTime\":1693640386000,\"updatedTime\":1693640386000,\"contributors\":[{\"name\":\"李子凡\",\"email\":\"3153566913@qq.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":2.4,\"words\":721},\"filePathRelative\":\"projects/zatan/9/2.md\",\"localizedDate\":\"2023年9月2日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
